server:
  port: ${PORT:8484}
  tomcat:
    basedir: logs
    accesslog:
      pattern: "%{yyyy-MM-dd HH:mm:ss.SSSZ}t %a %A '%{User-Agent}i' [%{Leap-Request-Context}o] %r %s %b %D"
      enabled: true
  servlet:
    context-path: /smartevents

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: smartevents
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: true
    validate-on-migrate: false
    schemas: smartevents
  datasource:
    url: jdbc:postgresql://localhost:5432/smartevents
    username: testuser
    password: pass
    driver-class-name: org.postgresql.Driver




